### ISSUE TITLE
GBFS issues

### ISSUE THREAD

**Issue by zabuTNT** [openmove/odh-mentor-otp#109]
There are some issues in GBFS produced:
v1 and v2.1:
https://gbfs-validator.netlify.app/?url=https%3A%2F%2Fgbfs.otp.opendatahub.bz.it%2Fbz%2F1%2Fgbfs.json
https://gbfs-validator.netlify.app/?url=https%3A%2F%2Fgbfs.otp.opendatahub.bz.it%2Fbz%2F2.1%2Fgbfs.json

**Comment by stefanocudini** [comment]
temporary PATCH here: https://github.com/openmove/odh-mentor-otp/commit/23e30a8382d84f579c0da180e68f47da290de163

**Comment by zabuTNT** [comment]
fixed with:
https://github.com/openmove/odh-mentor-otp/commit/0b2f160a41218c0cc9bea16f229c287455cf4b73
