### ISSUE TITLE
autofixing srtm bug

### ISSUE THREAD

**Issue by stemove** [openmove/odh-mentor-otp#13]
FIX DATI ALIMETRICI
issue aperto del building graph a causa dell'elevation file in TIFF.

https://github.com/opentripplanner/OpenTripPlanner/issues/2792

rileggendo mi sono anche ricordato ed è un problema di trasparenze, ad ogni modo con il comando:
gdal_edit.py -unsetnodata elevation_file.tif

**Comment by zabuTNT** [comment]
fix with a28f00497d2c44f5eee8a7bb8f78fcecca6339aa
