### ISSUE TITLE
build scss styles path by config

### ISSUE THREAD

**Issue by stefanocudini** [openmove/odh-mentor-otp#150]
obbiettivo e' che dobbiamo cercare di selezione scss da includere inwebpack da una configurazione di ambiente.
dal file config.yml oppure da una variabile di ambiente

https://github.com/openmove/odh-mentor-otp/blob/master/journey/src/main.js#L24

**Comment by stefanocudini** [comment]
solution:
https://stackoverflow.com/questions/59086681/sass-conditional-imports-based-on-env-variables-using-webpack-to-use-different
@RajaOpenMove

**Comment by stefanocudini** [comment]
solved in branch: https://github.com/openmove/odh-mentor-otp/tree/refact-styles-dir

**Comment by RajaOpenMove** [comment]
https://shipshape.io/blog/wait-for-page-load-in-react/

i think this could do something, i will try fully tomorrow

**Comment by stefanocudini** [comment]
TODO REFACT

**Comment by stefanocudini** [comment]
PATCH here: https://github.com/openmove/odh-mentor-otp/blob/dev/journey/src/app.js#L71

**Comment by stefanocudini** [comment]
[patch solved in fornace-ui](https://github.com/openmove/odh-mentor-otp/tree/fornace-ui)
