### ISSUE TITLE
navbar links configurable with modal

### ISSUE THREAD

**Issue by stefanocudini** [openmove/odh-mentor-otp#153]
- [x] each item in the menu must be taken from configuration
- [x] the entries must all be i18n therefore the texts must be inserted in the multi-language files

@RajaOpenMove   
- [x] let's make sure that from the configuration there are also a link with an entry from config "url" (in addition to the clickEvents methods)

- [x] we need to have oh generic/parametric(es. title, contents) method to show each section which or one html file for each section/modal

**Comment by stefanocudini** [comment]
- [ ] facciamo in modo che da config ci siano anche un link con una voce da condif tipo "url" esterno(oltre ai metodi clickEvents)

**Comment by stefanocudini** [comment]
@RajaOpenMove https://github.com/openmove/odh-mentor-otp/blob/new-vit/journey/src/app.js#L165

**Comment by RajaOpenMove** [comment]
this one you can close

**Comment by stefanocudini** [comment]
- [ ] we need to have oh generic method to show her each page which is parametric(eg title, content) or one html file for each modal

**Comment by stefanocudini** [comment]
https://github.com/openmove/odh-mentor-otp/tree/153-navbar-links-configurable-with-modal

**Comment by stefanocudini** [comment]
- [ ] check same logic in config.navList  and config.footer.navLinks
- [ ] rename config footer.navLinks in navList

**Comment by stefanocudini** [comment]
TODO Mobile but require a refactoring of html structure
