### ISSUE TITLE
stops request also when stop layer is disabled

### ISSUE THREAD

**Issue by stefanocudini** [openmove/odh-mentor-otp#158]
on map mouse move always new requests send, also stops layer is disabled
![stops](https://user-images.githubusercontent.com/47107/207058074-4e47afb2-c577-4d98-a1ca-cc359aec66e0.gif)

**Comment by RajaOpenMove** [comment]
how we can detect if layer is active or not, if you could help me with this i may know how to solve the rest

**Comment by RajaOpenMove** [comment]
this is not working yet
