### ISSUE TITLE
i18n otp-react-redux 

### ISSUE THREAD

**Issue by stemove** [openmove/odh-mentor-otp#16]
investigate if otp-ui support i18n

**Comment by zabuTNT** [comment]
No, it's not possible. 

We have to locate and translate every hardcoded string in otp-ui and otp-react-redux.  :-1:

**Comment by zabuTNT** [comment]
I'm Italianizing everything to understand how it is. I'm at a good point, it's not impossible.

**Comment by stemove** [comment]
someone simple i18n lib like this:
https://github.com/wikimedia/jquery.i18n

in theory just replace hardcoded strings with:
"TEXTenHARDcoded"  ->  $.i18n('IdText')

but anyway it could be very time consuming :(

**Comment by zabuTNT** [comment]
I forked 
https://github.com/openmove/otp-ui (master)
and
https://github.com/openmove/otp-react-redux (mentor-meran)

in order to work check the path for otp-ui packages in package.js in otp-react-redux

**Comment by stemove** [comment]
I need to clone manually otp-ui in otp-react-redux root path?

**Comment by stemove** [comment]
it should be possible to define dependencies via git... in ths way npm/yarn download automatically the cutom otp-ui
https://docs.npmjs.com/files/package.json#git-urls-as-dependencies

**Comment by zabuTNT** [comment]
@stemove 

`I need to clone manually otp-ui in otp-react-redux root path?`

No, I cloned otp-ui in folder above.
https://github.com/openmove/otp-react-redux/blob/mentor-meran/package.json#L30
and linked as they suggest in otp-ui readme.

`file:../otp-ui/packages/base-map`

**Comment by stemove** [comment]
I'm trying to join things together in docker with yarn ...

also the repo:
https://github.com/openmove/otp-ui

it should have a custom branch(having same name) for the fixes

**Comment by zabuTNT** [comment]
I'll investigate on this project that use otp-react-redux (it's the same company behind) as a library and it's more configurable:
https://github.com/ibi-group/trimet-mod-otp

**Comment by zabuTNT** [comment]
or use digitransit-ui that use metric system and maybe is more multilanguage-friendly:
https://github.com/HSLdevcom/digitransit-ui/blob/master/Dockerfile

???

**Comment by zabuTNT** [comment]
digitransit is too much linked with its ecosystem.
trimet-mod-otp is opt-rr with better ui (imho)

![2020-10-09-141017_1913x982_scrot](https://user-images.githubusercontent.com/5268372/95581467-6347de00-0a39-11eb-85ae-d0ecc03697f5.png)

**Comment by zabuTNT** [comment]
commit 654a16e3c5085daa2fc634dff73d0f21a1572711

**Comment by stemove** [comment]
on build image:
docker-compose build otp-app
...
```
ERROR in ./lib/main.js
Module not found: Error: Can't resolve 'otp-react-redux/dist/index.css' in '/otp-app/app-it/lib'
 @ ./lib/main.js 26:0-40
 @ multi ./lib/main.js ./lib/style.scss
Child html-webpack-plugin for "index.html":
         Asset     Size  Chunks  Chunk Names
    index.html  535 KiB       0  
    Entrypoint undefined = index.html
    [0] ./node_modules/html-webpack-plugin/lib/loader.js!./lib/index.tpl.html 640 bytes {0} [built]
    [1] ./node_modules/lodash/lodash.js 530 KiB {0} [built]
    [2] (webpack)/buildin/global.js 489 bytes {0} [built]
    [3] (webpack)/buildin/module.js 497 bytes {0} [built]
Child mini-css-extract-plugin node_modules/css-loader/index.js!node_modules/sass-loader/lib/loader.js!lib/style.scss:
    Entrypoint mini-css-extract-plugin = *
    [0] ./node_modules/css-loader!./node_modules/sass-loader/lib/loader.js!./lib/style.scss 12.7 KiB {0} [built]
    [1] ./node_modules/css-loader/lib/css-base.js 2.21 KiB {0} [built]

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: Service 'otp-app' failed to build: The command '/bin/sh -c cd /otp-app/app-it/ && 	yarn build && 	rm -f /var/www/html/index.nginx-debian.html && 	cp -fr dist /var/www/html/$FOLDER/' returned a non-zero code: 1

```

**Comment by zabuTNT** [comment]
It should be fixed now on development.

**Comment by zabuTNT** [comment]
I created a i18n system. It works for our use.
All strings are now: $_XXX_$. 
XXX is a key inside language.js that must be copied in dist folder.
Then at runtime on the browser these strings are replaced.

**Comment by stemove** [comment]
i18n switching work from this:
https://github.com/openmove/odh-mentor-otp/commit/c44eeb6ecaa996b32e7df9955c51e862cb0c1611
