### ISSUE TITLE
reload mechanism for Graph.obj

### ISSUE THREAD

**Issue by zabuTNT** [openmove/odh-mentor-otp#17]
http://dev.opentripplanner.org/apidoc/1.0.0/resource_Routers.html

In order to use "protected" endpoint you have to enable "Security":
http://docs.opentripplanner.org/en/latest/Security/

**Comment by stemove** [comment]
optionally we can:

add commands to shutdown the build machine and write logs

after otp production is reloaded.

**Comment by stemove** [comment]
created new branch fot testing this feature:
https://github.com/openmove/odh-mentor-otp/tree/reloading-otp

**Comment by zabuTNT** [comment]
Reloading graphs was implemented with commit
https://github.com/openmove/odh-mentor-otp/commit/5c8f0fabb522781f583ec39678ad861d8535d43c

**Comment by zabuTNT** [comment]
WARNING: for security reason OTP should protected by a firewall and **PUT/DELETE/POST requests should be filtered** based on request IP.

**Comment by zabuTNT** [comment]
Probably is better to use these "undocumented" flags when we start OTP:

`--autoReload`   automatic reload graphs if the files changed

and optional:

`--autoScan`     automatic search for routers in the folder graphs

so we can remove `--insecure`, and PUT/DELETE/POST won't be allowed

**Comment by stemove** [comment]
absolutely yes! this  is best solution

**Comment by zabuTNT** [comment]
remove --insecure option and add --autoReload with commit ab5794b29cf76783f1f51ebf791d5710ffcf9df5
