### ISSUE TITLE
Divide Routes lines 

### ISSUE THREAD

**Issue by Ghoster981** [openmove/odh-mentor-otp#174]
Since there are many lines, it would be better to divide them into pages or categories.
<img width="523" alt="image" src="https://user-images.githubusercontent.com/33777471/220839607-467851d1-149a-4adc-bf82-2e109d6b331a.png">

**Comment by stefanocudini** [comment]
https://github.com/openmove/odh-mentor-otp/tree/fix-route-viewer

**Comment by stefanocudini** [comment]
- [ ] todo pagination
