### ISSUE TITLE
Frontend: configuration

### ISSUE THREAD

**Issue by zabuTNT** [openmove/odh-mentor-otp#30]
configure /otp-app/config.yml

- [x] brand / title
- [x] subfolder (need it?)
- [x] otp url / port 
- [x] other settings

**Comment by stemove** [comment]
the best way is to use only the config.yml file and mount it as an external volume for Techpark customizations

environment variables I would leave them only for hosts and ports services names

**Comment by stemove** [comment]
> * subfolder (need it?)
@zabuTNT what subfolder?

**Comment by zabuTNT** [comment]
currently the dist folder is put in a subfolder, for example for italian language "it".
https://github.com/openmove/odh-mentor-otp/blob/4db203d440736e0c0582d11064c876de2ffccd42/otp-app/Dockerfile#L39
And german frontend will be put in "de". 

Other ideas?

**Comment by stemove** [comment]
otp url / port is the public doman view by browser..! not docker service name

for example for developement in localhost
```https://github.com/openmove/odh-mentor-otp/blob/development/docker-compose.yml#L18```
```API_HOST: http://localhost```

**Comment by stemove** [comment]
loook here:
https://github.com/openmove/odh-mentor-otp/commit/023311fa12448ca6b91cecaf2a873d8d5ab4a4a1

**Comment by zabuTNT** [comment]
@stemove 
Now the dist is inside: /var/www/html/dist and in order to see the app I have to write:
http://localhost:8070/dist/index.html

And if I click on "Ricomincia" I'm redirect on localhost:8070

there is a way to resolve this? Have we to copy the content of dist folder inside /var/www/html ?

**Comment by stemove** [comment]
this issue had escaped me!

**Comment by stemove** [comment]
@zabuTNT  solution to basepath redirect is here:
https://github.com/openmove/odh-mentor-otp/blob/development/otp-app/config.yml#L3

I'm trying

**Comment by zabuTNT** [comment]
yes I saw it, but the issue is about the port, if you click on "Ricomincia" it redirects you on http://localhost/<folder>, it removes 8070
