### ISSUE TITLE
add new env var for GTFS RT

### ISSUE THREAD

**Issue by stemove** [openmove/odh-mentor-otp#36]
add new environment var 

GTFS_RT_URL

and use it inside file ```router-config.json```

**Comment by stemove** [comment]
refact router-config.json suing json files.. instead of "script echo" generation
related to #8

**Comment by stemove** [comment]
example:
```json
"updaters": [
    {
      "id": "hsl-trip-updates",
      "type": "MQTT-gtfs-rt-updater",
      "url": "tcp://pred.rt.hsl.fi",
      "topic": "gtfsrt/v2/fi/hsl/tu",
      "feedId": "HSL",
      "fuzzyTripMatching": true
    },
]
```

**Comment by stemove** [comment]
{
            "type": "bike-rental",
            "sourceType": "bixi",
            "url": "https://www.capitalbikeshare.com/data/stations/bikeStations.xml",
            "frequencySec": -1
        },

{
          "type": "bike-rental",
          "frequencySec": 300,
          "sourceType": "gbfs",
          "url": "http://coast.socialbicycles.com/opendata/"
        },

**Comment by zabuTNT** [comment]
```
{
            "type": "stop-time-updater",
            "frequencySec": 60,
            // this is either http or file... shouldn't it default to http or guess from the presence of a URL?
            "sourceType": "gtfs-http",
            "url": "http://developer.trimet.org/ws/V1/TripUpdate/appID/0123456789ABCDEF",
            "feedId": "TriMet"
        }
```

```
{
            "type": "real-time-alerts",
            "frequencySec": 30,
            "url": "http://developer.trimet.org/ws/V1/FeedSpecAlerts/appID/0123456789ABCDEF",
            "feedId": "TriMet"
        },
```

**Comment by stemove** [comment]
creare prima gtfs trentino trasporti
e crare grafo

testing real-time-alerts
http://gtfs.openmove.com/tt
(protobuffer)

afgiunger 

testing
stop time updater
http://gtfs.openmove.com/autostradale
(protbuffer)

**Comment by stemove** [comment]
MENZ having only trips updates

verify it

**Comment by zabuTNT** [comment]
implemented with this commit 240cb66a561ee3ebcaac56d29be0da31b2bcb3bb

**Comment by zabuTNT** [comment]
but it still use the echo for the generation. reopen or create a new issue?

**Comment by stefanocudini** [comment]
solved here: https://github.com/openmove/odh-mentor-otp/commit/790170d2ac3ed590625b9c9588334cad3332968d
