### ISSUE TITLE
Strange call to docker causes crash of client app

### ISSUE THREAD

**Issue by stemove** [openmove/odh-mentor-otp#42]
original issue:
https://github.com/openmove/odh-mentor-otp/blob/9a7eb4832a1e4e67bd43e7198a7617ece79e33ff/infrastructure/ansible/hosts

unique config where shown is in this file:
```infrastructure/ansible/hosts```
https://github.com/openmove/odh-mentor-otp/blob/9a7eb4832a1e4e67bd43e7198a7617ece79e33ff/infrastructure/ansible/hosts

**Comment by stemove** [comment]
@zabuTNT may e this solve the problem:
https://github.com/openmove/odh-mentor-otp/commit/548c20acdf384508fa5db6f7e19a1fa73ea657d2

but... I can't replicate the bug on my localhost :(

**Comment by stefanocudini** [comment]
https://github.com/noi-techpark/odh-mentor-otp/issues/23
