### ISSUE TITLE
pass lang from react-ui to geocoder

### ISSUE THREAD

**Issue by stemove** [openmove/odh-mentor-otp#44]
investigate how to able this in react code

pass global var lang to request
https://github.com/openmove/odh-mentor-otp/blob/development/journey/app/lib/index.tpl.html#L55

**Comment by stefanocudini** [comment]
@valerio-fornace this is part of the i18n integration, but I could also fix it myself with your help once we have an i18n library integrated well

**Comment by stefanocudini** [comment]
TODO add new lang param here:
https://github.com/openmove/odh-mentor-otp/blob/fornace/journey/app/lib/otp-ui/geocoder/geocoders/pelias.js#L32

**Comment by valerio-fornace** [comment]
@stefanocudini take a look to this file to check how i18n works:
https://github.com/openmove/odh-mentor-otp/blob/fornace/journey/app/lib/components/form/date-time-preview.js
