### ISSUE TITLE
Stop Id in frontend

### ISSUE THREAD

**Issue by zabuTNT** [openmove/odh-mentor-otp#48]
The split <feedId>:<stopId> in case of GlobalID used by STA return only the element 1 of the array:  "it" and not the real stopId

`1:it:22021:2268:0:742 --> it (expected: it:22021:2268:0:742) `

`https://journey.opendatahub.testingmachine.eu/it/#/stop/1:it:22021:2268:0:742`

**Comment by stefanocudini** [comment]
sure not only 742?

**Comment by zabuTNT** [comment]
Yes, you're right, it could be the last value only.

**Comment by stefanocudini** [comment]
edits refernces:
https://github.com/openmove/odh-mentor-otp/blob/development/journey/app/otp-react-redux/lib/components/viewers/stop-viewer.js#L212

**Comment by stefanocudini** [comment]
fixed also agency id:
https://github.com/openmove/odh-mentor-otp/commit/c4dd683341b01276d59d1054434f09029eb8a1e6
