### ISSUE TITLE
Carsharing/CarRental: leg transit forced

### ISSUE THREAD

**Issue by zabuTNT** [openmove/odh-mentor-otp#53]
Actually, car rental is bound to transit, and if a transit leg is not found there is no solution.

this is hardcoded here: 

otp-ui/core-utils/src/query.js

```
    // set onlyTransitTrips for car rental searches
    if (params.mode && params.mode.includes("CAR_RENT")) {
      params.onlyTransitTrips = true;
    }
```

I suggest to set onlyTransitTrips = false, this way you can have mixed legs, but car_rent only solution, too.
![2021-03-18-143411_1264x900_scrot](https://user-images.githubusercontent.com/5268372/111634698-0bd34880-87f7-11eb-95da-d77e676e10d9.png)

**Comment by stefanocudini** [comment]
also here:
https://github.com/openmove/odh-mentor-otp/blob/master/journey/app/otp-react-redux/lib/actions/api.js#L296

**Comment by zabuTNT** [comment]
Another option is to remove the minTransitDistance.
```
 params.minTransitDistance = '50%'
```
It's true that i want a mixed solution but I couldn't force to give a transit solution if it's not possible (like when you receive only foot legs.)

As written in OpenTripPlanner:
```
// If this is a transit option and minTransitDistance is specified, do not include in plan if the
// itinerary's total transit distance is less than minTransitDistance
if (itinerary.transitTime > 0 && request.minTransitDistance != null) {
```

**Comment by stefanocudini** [comment]
TODO use env variable here:
https://github.com/openmove/odh-mentor-otp/blob/development/journey/config.yml#L145
