### ISSUE TITLE
Funicular mode is missing

### ISSUE THREAD

**Issue by zabuTNT** [openmove/odh-mentor-otp#54]
Funicular is available as mode of transport, but otp-react-redux doesn't support it. Modes of transport are hardcoded and limited to TRAM, RAIL,BUS and GONDOLA

**Comment by stefanocudini** [comment]
https://github.com/openmove/odh-mentor-otp/blob/development/journey/app/lib/otp-ui/core-utils/itinerary.js#L5

**Comment by zabuTNT** [comment]
real "all transit mode":

TRAM
SUBWAY
RAIL
BUS
CABLE_CAR
FERRY
GONDOLA
FUNICULAR
AIRPLANE

http://docs.opentripplanner.org/en/v1.5.0/Configuration/#routing-modes

**Comment by zabuTNT** [comment]
fixed by a15603e15e8310bf2eef04747f2286e88a3a90d8
