### ISSUE TITLE
traffic layer

### ISSUE THREAD

**Issue by stefanocudini** [openmove/odh-mentor-otp#55]
geometries:
https://mobility.api.opendatahub.bz.it/v2/flat,edge/LinkStation/?limit=-1&distinct=true&select=egeometry,ecode&where=eactive.eq.true

???:
traffic sensor
https://mobility.api.opendatahub.bz.it/v2/flat/TrafficSensor

link stations:
https://mobility.api.opendatahub.bz.it/v2/tree/LinkStation/*/latest?limit=-1&distinct=true&select=tmeasurements&where=sactive.eq.true,or(and(tname.eq.%22Bluetooth%20Elapsed%20time%20%5C(test%5C)%22))

**Comment by stefanocudini** [comment]
swagger dcos doesn't contains LinkStation:

https://swagger.opendatahub.bz.it/?url=https://mobility.api.opendatahub.bz.it/v2/apispec#/

**Comment by stefanocudini** [comment]
![traf](https://user-images.githubusercontent.com/47107/113689816-0026c380-96cb-11eb-800f-ec49756fdb58.png)

overlapping segments? :-/

**Comment by zabuTNT** [comment]
@stefanocudini multiple lanes and line too big?

**Comment by stefanocudini** [comment]
related to this: https://github.com/noi-techpark/odh-mentor-otp/issues/86

**Comment by stefanocudini** [comment]
example of usage
https://github.com/noi-techpark/it.bz.opendatahub.analytics

config color by values:
https://github.com/noi-techpark/it.bz.opendatahub.analytics/blob/master/src/main/webapp/linkstation-config.json

**Comment by stefanocudini** [comment]
in branch https://github.com/openmove/odh-mentor-otp/tree/traffic

**Comment by stefanocudini** [comment]
https://github.com/openmove/odh-mentor-otp/commit/8366449d4c02515d209f9ffb36c1b5d3497d4e46

**Comment by stefanocudini** [comment]
for google traffic data
https://github.com/aviklai/react-leaflet-google-layer
