### ISSUE TITLE
E-chargers as markers on map

### ISSUE THREAD

**Issue by zabuTNT** [openmove/odh-mentor-otp#60]
The endpoint that return charger haven't a bbox filter or something like that:

https://github.com/openmove/odh-mentor-otp/blob/development/charger/index.js#L73

There are many chargers, so if you draw all the markers could be a problem.

The frontend shouldn't receive all the chargers, but only the charger to display on map and only below a certain zoom.

**Comment by stefanocudini** [comment]
example of pass bbox via leaflet-jsonlayer
https://github.com/stefanocudini/leaflet-layerJSON/blob/master/examples/overpass.html#L39

**Comment by zabuTNT** [comment]
Now charger endpoint accept bbox as query parameter, in order to filter the results
https://github.com/openmove/odh-mentor-otp/commit/35844356ddabe3b279c86cb092ad00b1e415e429

**Comment by zabuTNT** [comment]
what to do with private e-chargers ? 

for instance:

```
{
"station_id": "ASD_00000055",
"name": "THALHOF",
"lat": 46.386265,
"lon": 11.255079,
"provider": "Neogy",
"address": "Hotel Thalhof - Lago di Caldaro - Kalterersee 10",
"city": "Caldaro S. S. V. - Kaltern A. D. W.",
"accessType": "PRIVATE",
"capacity": 1,
"reservable": false,
"state": "ACTIVE",
"plugs": [
{
"plug_id": "ASD_00000055-1",
"name": "THALHOF-IT*ASD*E1688*7*7*7*0020*8*8*8*17*1",
"available": true,
"maxPower": 7.345,
"maxCurrent": 32,
"minCurrent": 7,
"outletTypeCode": "Type2Mennekes"
}
]
},
```

this is a e-charger of an hotel, should we display it or not? Or display it with a different badge/label? Write that is for private uses in the popup?
