### ISSUE TITLE
from button over parking dont work for planning

### ISSUE THREAD

**Issue by stefanocudini** [openmove/odh-mentor-otp#63]
![Screenshot at 2021-06-11 13-19-52](https://user-images.githubusercontent.com/47107/121678738-d79abb80-cab7-11eb-971a-7e6ee3c2efba.png)

**Comment by stefanocudini** [comment]
@valerio-fornace 
this seems to me that in the beginning it worked.

between two bikesharing markers works, I think it is a simple problem

**Comment by stefanocudini** [comment]
event over parking is not triggered

![park](https://user-images.githubusercontent.com/47107/124572612-0f8fe700-de49-11eb-96eb-d229d8e29920.gif)

**Comment by valerio-fornace** [comment]
ok it works now. Please try and let me know

**Comment by valerio-fornace** [comment]
@stefanocudini is this closed?

**Comment by stefanocudini** [comment]
some overlapping markers remain, but it is not important, maybe I can see how to solve

![Screenshot at 2021-07-13 13-25-55](https://user-images.githubusercontent.com/47107/125444571-f3ced8c2-5660-4404-9c01-8fe37c8ff85d.png)

**Comment by stefanocudini** [comment]
also it could be logical that there is overlapped
