### ISSUE TITLE
add  on-street parking layers

### ISSUE THREAD

**Issue by stefanocudini** [openmove/odh-mentor-otp#70]
data source: https://parking.otp.opendatahub.testingmachine.eu/parking/sensors.json

additional layer similar to parking

**Comment by zabuTNT** [comment]
similar to parking, but maybe different icon (?) in order to inderstood that is a single slot. Maybe not. 
popup should say if it's free or not. The badge could be only red or 1 (free).

**Comment by stefanocudini** [comment]
![image](https://user-images.githubusercontent.com/47107/126749502-6974f04b-329a-4260-9ff0-86b38f181975.png)
