### ISSUE TITLE
simple overlay for credits

### ISSUE THREAD

**Issue by stefanocudini** [openmove/odh-mentor-otp#72]
adding button to open an Overlay/Modal that contains credits of project

adding title/contents texts in i18n labels

**Comment by valerio-fornace** [comment]
@stefanocudini do you have an idea about the content that we will put in modal? Do you just have some copy or can i put lorem ipsum text in the meanwhile?

**Comment by valerio-fornace** [comment]
@stefanocudini i did it but i will wait text before to close it

**Comment by stefanocudini** [comment]
please add some empty texts in i18n

for example
- credits_title
- credits_text

then after we will think about the content

**Comment by stefanocudini** [comment]
@valerio-fornace  we also need a link for credits modal ...

it might be a good idea to insert it at the bottom of the panel or on one side of the navbar
or in the attribution of the leaflet map

the choice is yours UX experts :)

**Comment by valerio-fornace** [comment]
@stefanocudini you mean a link with slug or with hash?

**Comment by stefanocudini** [comment]
yes for example _/#/credits_

**Comment by valerio-fornace** [comment]
@stefanocudini now there is the button on navbar. On click modal will open without change url but if you arrive on app from "/#/credits" the modal will open automatically. In this way you can spread this url wherever you want
