### ISSUE TITLE
Selected Stops color hardcoded "cyan"

### ISSUE THREAD

**Issue by zabuTNT** [openmove/odh-mentor-otp#77]
When zoom out

![2021-07-16-095935_917x860_scrot](https://user-images.githubusercontent.com/5268372/125913518-7007c671-e71b-454a-beb0-4f65047d4bab.png)

find a better color, or get from settings

**Comment by stefanocudini** [comment]
inverted color
![image](https://user-images.githubusercontent.com/47107/126490103-0c174d23-e384-481f-86ec-1cdf52aafdd4.png)
