### ISSUE TITLE
fix poup charger and car sharing

### ISSUE THREAD

**Issue by stefanocudini** [openmove/odh-mentor-otp#79]
@valerio-fornace I try here but i can't build the colored dots as per mockup
https://github.com/openmove/odh-mentor-otp/commit/1208739175dbef8b8e8f51beb773a7a4161816d8
![mock](https://user-images.githubusercontent.com/47107/126480225-6d0fa8e0-4022-4f7d-8109-7e951c195396.png)

![charge](https://user-images.githubusercontent.com/47107/126480114-ab3b5ae4-10f2-4701-8597-e20994ddf821.gif)

**Comment by valerio-fornace** [comment]
done!
