### ISSUE TITLE
i18next does not remember the language user selection

### ISSUE THREAD

**Issue by stefanocudini** [openmove/odh-mentor-otp#88]
this is strange because it reminds me that it worked

I also tried to include the i18next storage module but it doesn't seem to work:
https://github.com/openmove/odh-mentor-otp/commit/33777eebbceec9ae89b8d82e4a0e61c9898e1332

@valerio-fornace I think something is broken and yet there are no errors in the console

**Comment by valerio-fornace** [comment]
Hei Ste! I fix this bug. With refactor i forgot to store language in localstorage on language change event by user. 
Please pull from feature/fornace_ui to see changes.
